version: "3.8"

services:
  client:
    # Telling docker-compose to build the client image using the Dockerfile in the client directory.
    build: ./client
    # Giving the container a name.
    container_name: booktalks-client
    # Mapping the port 3000 on the host machine to the port 3000 on the container.
    ports:
      - "3000:3000"

  server:
    # Telling docker-compose to build the server image using the Dockerfile in the server directory.
    build: ./server
    container_name: booktalks-server
    ports:
      - "5000:5000"